### ISSUE TITLE
Simple suggestion - reference the source URL and license right in the shell script?

### ISSUE THREAD

**Issue by Michael-S** [jgamblin/quickinstall#1]
That's a handy script, thanks for writing it.  Do you think it makes sense to put the git repository URL and a reference to the MIT License right in the script itself?   Obviously if I clone the repository I get all of that information automatically, but if I just download the script I have to add it myself or else I lose it and have to hunt it down if I want it.

**Comment by jgamblin** [comment]
I dont mind adding this if you can tell me how I would do it?  What would the verbage look like?

**Comment by Michael-S** [comment]
Oh, I just meant adding something like this near the top of the shell script (obviously below the shebang line):

# Copyright 2016, jgamblin, released under the MIT License 
# See https://github.com/jgamblin/quickinstall/blob/master/LICENSE for the
# complete license text
# Source code at https://github.com/jgamblin/quickinstall

Or anything simple like that.  Thanks.

**Comment by jgamblin** [comment]
Thanks, I just wanted to know what you would like to see.   I will add it.  : )

**Comment by jgamblin** [comment]
Fixed.  : )

**Comment by Michael-S** [comment]
Thank you.
